export const studioData = [
    {"studio": "Madhouse", "trakt_id": 1218},
    {"studio": "Wit Studio", "trakt_id": 1247},
    {"studio": "Mappa", "trakt_id": 1228},
    {"studio": "BONES", "trakt_id": 1355},
    {"studio": "Aniplex", "trakt_id": 1297},
    {"studio": "J.C.Staff", "trakt_id": 176},
    {"studio": "Kyoto Animation", "trakt_id": 1722},
    {"studio": "Toei  Animation", "trakt_id": 590},
    {"studio": "TRIGGER", "trakt_id": 1603},
    {"studio": "P.A.Works", "trakt_id": 1512},
    {"studio": "Shueisha", "trakt_id": 305},
    {"studio": "Production I.G", "trakt_id": 215},
    {"studio": "twin engine", "trakt_id": 1069},
    {"studio": "olm", "trakt_id": 1303},
    {"studio": "TV Tokyo", "trakt_id": 306},
    {"studio": "Pierrot", "trakt_id": 1122},
    {"studio": "ufotable", "trakt_id": 1163},
    {"studio": "A-1 Pictures", "trakt_id": 578},
    {"studio": "Bandai Namco Entertainment", "trakt_id": 2549},
    {"studio": "SUNRISE", "trakt_id": 1248},
    {"studio": "Brain's Base", "trakt_id": 1514},
    {"studio": "AIC PLUS+", "trakt_id": 1623},
    {"studio": "FUNimation Entertainment", "trakt_id": 1194},
    {"studio": "Crunchyroll", "trakt_id": 15770},
    {"studio": "Sony Music Entertainment Japan", "trakt_id": 3342},
    {"studio": "Mainichi Broadcasting System (MBS)", "trakt_id": 2477},
    {"studio": "Sound Box", "trakt_id": 2123},
    {"studio": "LIDENFILMS", "trakt_id": 574},
    {"studio": "Techno Sound", "trakt_id": 100034},
    {"studio": "Square Enix", "trakt_id": 1354},
    {"studio": "bandai", "trakt_id": 81},
    {"studio": "Fuji Television Network", "trakt_id": 604},
    {"studio": "mini art", "trakt_id": 3158},
    {"studio": "movic", "trakt_id": 2368},
    {"studio": "Yomiuri Telecasting Corporation (YTV)", "trakt_id": 2858},
    {"studio": "dentsu", "trakt_id": 1506},
    {"studio": "Toho Company, Ltd.", "trakt_id": 2990},
    {"studio": "Skydance Television", "trakt_id": 614},
    {"studio": "No Brakes", "trakt_id": 187486},
    {"studio": "Sumzap", "trakt_id": 106612},
    {"studio": "Zack Promotion", "trakt_id": 136579},
    {"studio": "SATELIGHT", "trakt_id": 1188},
    {"studio": "bilibili", "trakt_id": 24523},
    {"studio": "David Production", "trakt_id": 952},
    {"studio": "DMM Music", "trakt_id": 109240},
    {"studio": "Kodansha", "trakt_id": 2369},
    {"studio": "Bandai Visual", "trakt_id": 81},
    {"studio": "Drive (JP)", "trakt_id": 2690},
    {"studio": "Studio Deen", "trakt_id": 1360},
]
